white space and consistency cleanup on bin/
All programs in bin/ have 4 space indent and consistent 'vi:' settings
set at bottom of file.
   # vi: tabstop=4 expandtab

For consistency and simplicity, all programs in bin/ are bash as opposed
to mixed bash or sh.

diff --git a/bin/build-arch b/bin/build-arch
--- a/bin/build-arch
+++ b/bin/build-arch
@@ -1,11 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 
 Usage() {
-   cat <<EOF
+    cat <<EOF
 ${0##*/} buildroot-dir arch output [confd]
 
-  build the buildroot dir in buildroot-dir
-  put output in output. confd defaults to topdir/conf
+    build the buildroot dir in buildroot-dir
+    put output in output. confd defaults to topdir/conf
 EOF
 }
 
@@ -13,7 +13,7 @@ error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 
 [ $# -eq 3 -o $# -eq 4 ] ||
-   { Usage 1>&2; exit 1; }
+    { Usage 1>&2; exit 1; }
 [ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }
 
 
@@ -25,7 +25,7 @@ confd=""
 [ $# -eq 0 ] && set -- make
 
 [ -n "$confd" ] || confd=$( cd "${0%/*}/../conf" && pwd) ||
-   fail "failed to find conf dir"
+    fail "failed to find conf dir"
 
 mkdir -p "$out" || fail "failed to make outdir $out"
 out=$(cd "${out}" && pwd)
@@ -38,3 +38,5 @@ out=$(cd "${out}" && pwd)
 
 cd "$bdir" 
 make "O=$BR_OUT" "BUSYBOX_CONFIG_FILE=$out/busybox.config" "$@"
+
+# vi: tabstop=4 expandtab
diff --git a/bin/build-initramfs b/bin/build-initramfs
--- a/bin/build-initramfs
+++ b/bin/build-initramfs
@@ -1,44 +1,43 @@
 #!/bin/bash
-# vi: ts=4 noexpandtab
 
 TEMP_D=""
 
 error() { echo "$@" 1>&2; }
 debug() {
-	[ "${DEBUG}" -ge "${1}" ] || return 0;
-	shift;
-	error "$@"
+    [ "${DEBUG}" -ge "${1}" ] || return 0;
+    shift;
+    error "$@"
 }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 Usage() {
-	cat <<EOF
+    cat <<EOF
 Usage: ${0##*/} initramfs_dir root_dir
-   create an initramfs from initramfs_dir, copying files from root_dir
+    create an initramfs from initramfs_dir, copying files from root_dir
 
-   Example:
-    ${0##*/} initramfs/ rootfs/ > my.initramfs.img
+    Example:
+     ${0##*/} initramfs/ rootfs/ > my.initramfs.img
 EOF
 }
 bad_Usage() { Usage 1>&2; fail "$@"; }
 cleanup() {
-	[ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
+    [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
 }
 
 short_opts="hv"
 long_opts="help,verbose"
 getopt_out=$(getopt --name "${0##*/}" \
-	--options "${short_opts}" --long "${long_opts}" -- "$@") &&
-	eval set -- "${getopt_out}" ||
-	bad_Usage
+    --options "${short_opts}" --long "${long_opts}" -- "$@") &&
+    eval set -- "${getopt_out}" ||
+    bad_Usage
 
 while [ $# -ne 0 ]; do
-	cur=${1}; next=${2};
-	case "$cur" in
-		-h|--help) Usage; exit 0;;
-		-v|--verbose) DEBUG=$((${DEBUG}+1));;
-		--) shift; break;;
-	esac
-	shift;
+    cur=${1}; next=${2};
+    case "$cur" in
+        -h|--help) Usage; exit 0;;
+        -v|--verbose) DEBUG=$((${DEBUG}+1));;
+        --) shift; break;;
+    esac
+    shift;
 done
 
 [ $# -eq 2 ] || bad_Usage "must give initramfs_dir and root_dir"
@@ -49,7 +48,7 @@ root_d=${2}
 [ -d "$root_d" ] || fail "$root_d is not a dir"
 
 TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/.${0##*/}.XXXXXX") ||
-	fail "failed to make tempd"
+    fail "failed to make tempd"
 trap cleanup EXIT
 
 work_d="${TEMP_D}/workd"
@@ -62,32 +61,34 @@ needs="$initramfs_d/needs"
 mkdir -p "${work_d}/"{bin,sbin,usr/bin,usr/sbin}
 
 while read need; do
-	need=${need%%#*}; need=${need% };
-	[ -n "$need" ] || continue
-	[ "${need#*..}" = "${need}" ] || fail "paths cannot have ..: $need"
-	if [ -e "$root_d/$need" ]; then
-		mkdir -p "$work_d/${need%/*}" &&
-		cp -a "$root_d/$need" "$work_d/$need" ||
-		fail "failed to copy $need to working dir"
-	else
-		fail "$need not found in $root_d"
-	fi
+    need=${need%%#*}; need=${need% };
+    [ -n "$need" ] || continue
+    [ "${need#*..}" = "${need}" ] || fail "paths cannot have ..: $need"
+    if [ -e "$root_d/$need" ]; then
+        mkdir -p "$work_d/${need%/*}" &&
+        cp -a "$root_d/$need" "$work_d/$need" ||
+        fail "failed to copy $need to working dir"
+    else
+        fail "$need not found in $root_d"
+    fi
 done < $needs
 
 loaders=$(cd "$root_d" &&
-	echo lib/ld-uClibc.so.0 lib/ld-uClibc-*.so \
-		lib/ld64-uClibc.so.0 lib/ld64-uClibc-*.so)
+    echo lib/ld-uClibc.so.0 lib/ld-uClibc-*.so \
+        lib/ld64-uClibc.so.0 lib/ld64-uClibc-*.so)
 
 for f in $loaders; do
-	[ -f "$root_d/$f" ] || continue
-	mkdir -p "${work_d}/${f%/*}" &&
-	cp -a "$root_d/$f" "$work_d/$f" ||
-		fail "failed to copy $f"
+    [ -f "$root_d/$f" ] || continue
+    mkdir -p "${work_d}/${f%/*}" &&
+    cp -a "$root_d/$f" "$work_d/$f" ||
+        fail "failed to copy $f"
 done
 
 rsync -a "$src_d/" "$work_d" ||
-	fail "failed to sync $src_d to working dir"
+    fail "failed to sync $src_d to working dir"
 
 ( cd "${work_d}" && find . | cpio --quiet --dereference -o -H newc | gzip -9 )
 
 exit 0
+
+# vi: tabstop=4 expandtab
diff --git a/bin/bundle b/bin/bundle
--- a/bin/bundle
+++ b/bin/bundle
@@ -1,6 +1,4 @@
 #!/bin/bash
-# vi: ts=4 noexpandtab
-#
 
 TEMP_D=""
 UMOUNT=""
@@ -10,17 +8,17 @@ DEF_MODULES="acpiphp e1000 ne2k-pci 8139cp pcnet32 ip_tables"
 
 error() { echo "$@" 1>&2; }
 debug() {
-	[ "${DEBUG}" -ge "${1}" ] || return 0;
-	shift;
-	error "$@"
+    [ "${DEBUG}" -ge "${1}" ] || return 0;
+    shift;
+    error "$@"
 }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 Usage() {
-	cat <<EOF
+    cat <<EOF
 Usage: ${0##*/} rootfs.tar kpkg.deb output_dir
-   [re]Bundle a buildroot rootfs into a mini-cloud image
+    [re]Bundle a buildroot rootfs into a mini-cloud image
 
-   options:
+    options:
      -s | --size S            resize image to size (default: ${DEF_SIZE})
           --arch A            prepare for arch A
 
@@ -30,19 +28,19 @@ EOF
 }
 bad_Usage() { Usage 1>&2; fail "$@"; }
 cleanup() {
-	[ -z "${UMOUNT}" ] || umount "${UMOUNT}"
-	[ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
+    [ -z "${UMOUNT}" ] || umount "${UMOUNT}"
+    [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
 }
 xrsync() {
-	rsync --archive --xattrs --hard-links --acls --sparse "$@"
+    rsync --archive --xattrs --hard-links --acls --sparse "$@"
 }
 
 short_opts="hs:v"
 long_opts="arch:,initrd-busybox:,help,size:,verbose"
 getopt_out=$(getopt --name "${0##*/}" \
-	--options "${short_opts}" --long "${long_opts}" -- "$@") &&
-	eval set -- "${getopt_out}" ||
-	bad_Usage
+    --options "${short_opts}" --long "${long_opts}" -- "$@") &&
+    eval set -- "${getopt_out}" ||
+    bad_Usage
 
 topdir=$(cd "${0%/*}/.." && pwd)
 size=${DEF_SIZE}
@@ -51,15 +49,15 @@ fs_type="ext3"
 arch=""
 
 while [ $# -ne 0 ]; do
-	cur=${1}; next=${2};
-	case "$cur" in
-		-h|--help) Usage; exit 0;;
-		-s|--size) size=${next}; shift;;
-		   --arch) arch=${next}; shift;;
-		-v|--verbose) DEBUG=$((${DEBUG}+1));;
-		--) shift; break;;
-	esac
-	shift;
+    cur=${1}; next=${2};
+    case "$cur" in
+        -h|--help) Usage; exit 0;;
+        -s|--size) size=${next}; shift;;
+           --arch) arch=${next}; shift;;
+        -v|--verbose) DEBUG=$((${DEBUG}+1));;
+        --) shift; break;;
+    esac
+    shift;
 done
 
 [ $# -eq 3 ] || bad_Usage "must give rootfs.tar, kernel pkg, out_dir"
@@ -79,13 +77,13 @@ xgrubd="$topdir/grubd"
 [ -d "${src_dir}" ] || fail "no source dir ${src_d}"
 
 TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/.${0##*/}.XXXXXX") ||
-	fail "failed to make tempd"
+    fail "failed to make tempd"
 trap cleanup EXIT
 
 mkdir -p "${out_d_in}" && out_d=$(readlink -f "${out_d_in}") &&
-	rootfs=$(readlink -f "${rootfs_in}") &&
-	kpkg=$(readlink -f "${kpkg_in}") ||
-	fail "failed to get full path for input"
+    rootfs=$(readlink -f "${rootfs_in}") &&
+    kpkg=$(readlink -f "${kpkg_in}") ||
+    fail "failed to get full path for input"
 
 out_partimg="${out_d}/part.img"
 out_diskimg="${out_d}/disk.img"
@@ -112,199 +110,200 @@ filesys_tar="$inter_d/filesys.tar"
 
 modfile="$src_dir/etc/modules"
 if [ -f "$modfile" ]; then
-	MODULES=$("$src_dir/etc/init.d/load-modules" parse_modules \
+    MODULES=$("$src_dir/etc/init.d/load-modules" parse_modules \
         "$modfile" "$arch") ||
-		fail "failed to read modules"
-	MODULES=$(echo "$MODULES" | sed 's, .*,,' | tr '\n' ' ')
+        fail "failed to read modules"
+    MODULES=$(echo "$MODULES" | sed 's, .*,,' | tr '\n' ' ')
 else
-	MODULES=${DEF_MODULES}
+    MODULES=${DEF_MODULES}
 fi
 debug 1 "modules: $MODULES"
 
 prepare-grub "$xgrubd" ||
-	fail "failed to get grub binary"
+    fail "failed to get grub binary"
 
 mkdir -p "${mp}" "${kernel_d}" "${overlay_d}" \
-	"${initramfs_d}" "$inter_d" "$stage_d" ||
-	fail "failed to make temp dirs"
+    "${initramfs_d}" "$inter_d" "$stage_d" ||
+    fail "failed to make temp dirs"
 
 debug 1 "creating filesystem in ${out_partimg}"
 rm -f "$out_partimg"
 truncate "--size=${size}" "${out_partimg}" ||
-	fail "failed to create ${out_partimg} of size ${size}"
+    fail "failed to create ${out_partimg} of size ${size}"
 
 out=$("mkfs.${fs_type}" -F "${out_partimg}" -L "${FS_LABEL}" 2>&1) ||
-	fail "failed to make filesystem of type ${fs_type}: ${out}" 
+    fail "failed to make filesystem of type ${fs_type}: ${out}" 
 
 cp "$out_partimg" "$out_blankimg" ||
-	fail "failed to to copy blank partition image"
+    fail "failed to to copy blank partition image"
 
 debug 1 "preparing kernel overlay"
 # creating kernel tarball
 case "$kpkg_in" in
-	*.deb)
-		dpkg -x "${kpkg_in}" "${kernel_d}" ||
-			fail "failed extracting kernel deb package in ${kpkg_in}"
-		;;
-	*.tar*)
-		tar -C "$kernel_d" -xf "$kpkg_in" ||
-			fail "failed extracting kernel tarball in ${kpkg_in}"
-		;;
-	*) fail "unknown file format for $kpkg_in";;
+    *.deb)
+        dpkg -x "${kpkg_in}" "${kernel_d}" ||
+            fail "failed extracting kernel deb package in ${kpkg_in}"
+        ;;
+    *.tar*)
+        tar -C "$kernel_d" -xf "$kpkg_in" ||
+            fail "failed extracting kernel tarball in ${kpkg_in}"
+        ;;
+    *) fail "unknown file format for $kpkg_in";;
 esac
 
 ( cd "${kernel_d}" && find * -type f ) > "${kern_list_full}" ||
-	fail "failed to extract kernel to ${kernel_d}"
+    fail "failed to extract kernel to ${kernel_d}"
 
 kver=""
 for x in "$kernel_d/lib/modules"/*; do
-	[ -d "$x/kernel" ] || continue
-	[ -z "$kver" ] ||
-		fail "2 or more things looked like kernels in lib/modules of $kpkg_in"
-	kver="${x##*/}"
+    [ -d "$x/kernel" ] || continue
+    [ -z "$kver" ] ||
+        fail "2 or more things looked like kernels in lib/modules of $kpkg_in"
+    kver="${x##*/}"
 done
 [ -n "$kver" ] ||
-	fail "failed to find kernel version. no lib/modules/* ?"
+    fail "failed to find kernel version. no lib/modules/* ?"
 
 depmod -a --basedir "${kernel_d}" "${kver}" ||
-	fail "failed to run depmod"
+    fail "failed to run depmod"
 
 mdep="${kernel_d}/lib/modules/${kver}/modules.dep"
 for x in ${MODULES}; do
-	grep -q "/${x}.ko" "${mdep}" ||
-		{ error "WARNING: no ${x} in kernel package!"; continue; }
-	awk -F: '$1 ~ mat {
-		sub(":","",$1)
-		printf("%s/%s\n",p,$1)
-		leng=split($0,deps," ")
-		x=2 # strange, but 0 contains nothing, 1 contains first field (with :)
-		while ( x<=leng ) {
-			printf("%s/%s\n", p, deps[x]);
-			x++
-		}
-	}' mat="/${x}.ko$" p="lib/modules/${kver}" "${mdep}"
+    grep -q "/${x}.ko" "${mdep}" ||
+        { error "WARNING: no ${x} in kernel package!"; continue; }
+    awk -F: '$1 ~ mat {
+        sub(":","",$1)
+        printf("%s/%s\n",p,$1)
+        leng=split($0,deps," ")
+        x=2 # strange, but 0 contains nothing, 1 contains first field (with :)
+        while ( x<=leng ) {
+            printf("%s/%s\n", p, deps[x]);
+            x++
+        }
+    }' mat="/${x}.ko$" p="lib/modules/${kver}" "${mdep}"
 done > "${kern_modules}"
 sort -u "${kern_modules}" > "${kern_files}"
 vmlinuz=$( cd "${kernel_d}" && [ -f boot/vmlinu?-* ] &&
-	echo boot/vmlinu?-* ) && echo "${vmlinuz}" >> "${kern_files}" &&
-	ln -sf "$vmlinuz" "$kernel_d/vmlinuz" && echo "vmlinuz" >> "$kern_files" ||
-	fail "no kernel (boot/vmlinuz-*) found in ${kpkg_in}"
+    echo boot/vmlinu?-* ) && echo "${vmlinuz}" >> "${kern_files}" &&
+    ln -sf "$vmlinuz" "$kernel_d/vmlinuz" && echo "vmlinuz" >> "$kern_files" ||
+    fail "no kernel (boot/vmlinuz-*) found in ${kpkg_in}"
 echo "boot/config-$kver" >> "$kern_files"
 
 tar -C "${kernel_d}" -cpf - \
-	--files-from "${kern_files}" > "${kernel_tar}" ||
-	fail "failed to collect kernel files"
+    --files-from "${kern_files}" > "${kernel_tar}" ||
+    fail "failed to collect kernel files"
 
 debug 1 "preparing source overlay from ${src_dir}"
 xrsync "${src_dir}/" "${overlay_d}" ||
-	fail "failed to copy source dir"
+    fail "failed to copy source dir"
 
 chown -R 0:0 "${overlay_d}" || fail "failed to chown files in overlay"
-	
+    
 if [ -f "${src_symlinks}" ]; then
-	( cd "${overlay_d}" &&
-		while read src target; do
-			{ [ -d "${target%/*}" ] || mkdir -p "${target%/*}"; } ||
-				{ error "could not create ${target%/*}"; exit 1; }
-			ln -sf "${src}" "${target}" || exit 1
-		done < "${src_symlinks}"
-	) || fail "failed to create symlinks"
+    ( cd "${overlay_d}" &&
+        while read src target; do
+            { [ -d "${target%/*}" ] || mkdir -p "${target%/*}"; } ||
+                { error "could not create ${target%/*}"; exit 1; }
+            ln -sf "${src}" "${target}" || exit 1
+        done < "${src_symlinks}"
+    ) || fail "failed to create symlinks"
 fi
 if [ -f "${makedevs_list}" ]; then
-	xmakedevs "$makedevs_list" "$overlay_d" ||
-		fail "failed to makedevs on overlay"
+    xmakedevs "$makedevs_list" "$overlay_d" ||
+        fail "failed to makedevs on overlay"
 fi
 
 ( cd "$overlay_d" && tar -cpf - * ) > "$overlay_tar" ||
-	fail "failed to make overlay_tar"
+    fail "failed to make overlay_tar"
 
 debug 1 "populating staging directory"
 tar -C "$stage_d" -xpf - < "$rootfs_in" ||
-	fail "failed to extract rootfs_tar"
+    fail "failed to extract rootfs_tar"
 tar -C "$stage_d" -xpf - < "$overlay_tar" ||
-	fail "failed to extract overlay_tar"
+    fail "failed to extract overlay_tar"
 
 if [ -x "${fixup_fs}" ]; then
-	"${fixup_fs}" "${stage_d}" ||
-		fail "failed to fixup filesystem"
+    "${fixup_fs}" "${stage_d}" ||
+        fail "failed to fixup filesystem"
 fi
 
 ( cd "$stage_d" && tar -Scpzf - -- * ) > "$out_filesys_lxc" ||
-	fail "failed to create filesys tarball"
+    fail "failed to create filesys tarball"
 
 tar -C "$stage_d" -xpf - < "$kernel_tar" ||
-	fail "failed to extract kernel_tar"
+    fail "failed to extract kernel_tar"
 tar -C "$stage_d" -xpf - < "$xgrubd/bootgrub.tar" ||
-	fail "failed to extract bootgrub"
+    fail "failed to extract bootgrub"
 
 depmod -a --basedir "$stage_d" "${kver}" ||
-	fail "failed to run depmod for kver ${kver} in output"
+    fail "failed to run depmod for kver ${kver} in output"
 
 debug 1 "creating initramfs"
 xrsync "$stage_d/" "$initramfs_d" ||
-	fail "failed to copy to initramfs_d"
+    fail "failed to copy to initramfs_d"
 rm -Rf "$initramfs_d/vmlinuz" "$initramfs_d/boot" ||
-	fail "failed to remove files in initramfs staging dir"
+    fail "failed to remove files in initramfs staging dir"
 
 ( cd "$initramfs_d" && find . | cpio --quiet -o -H newc |
-	gzip -9 ) > "$initramfs"
+    gzip -9 ) > "$initramfs"
 
 rm -Rf "$initramfs_d/lib/modules/$kver" ||
-	fail "failed to remove lib/modules for mini initramfs"
+    fail "failed to remove lib/modules for mini initramfs"
 
 ( cd "$initramfs_d" && find . | cpio --quiet -o -H newc |
-	gzip -9 ) > "${initramfs}.smaller"
+    gzip -9 ) > "${initramfs}.smaller"
 
 cp "${initramfs}.smaller" "$stage_d/boot/initrd.img-${kver}" &&
-	ln -s "boot/initrd.img-${kver}" "${stage_d}/initrd.img" ||
-	fail "failed to copy initramfs to stage dir"
+    ln -s "boot/initrd.img-${kver}" "${stage_d}/initrd.img" ||
+    fail "failed to copy initramfs to stage dir"
 
 debug 1 "packing clean kernel_tar"
 tar -C "$stage_d" -cpf - \
-	vmlinuz initrd.img boot/ lib/modules/ > "$kernel_tar" ||
-	fail "failed to create clean kerne_tar"
+    vmlinuz initrd.img boot/ lib/modules/ > "$kernel_tar" ||
+    fail "failed to create clean kerne_tar"
 
 ( cd "$stage_d" && tar -cpf - * ) > "$filesys_tar" ||
-	fail "failed to create filesys_tar"
+    fail "failed to create filesys_tar"
 
 debug 1 "populating image"
 mount -o loop "${out_partimg}" "${mp}" && UMOUNT=${mp} ||
-	fail "failed to mount ${out_partimg} loopback"
+    fail "failed to mount ${out_partimg} loopback"
 
 tar -C "$mp" -xpf - < "$filesys_tar" ||
-	fail "failed to populate mount point"
+    fail "failed to populate mount point"
 
 umount "${mp}" && UMOUNT="" ||
-	fail "failed to unmount ${out_partimg}"
+    fail "failed to unmount ${out_partimg}"
 
 cp "${kernel_d}/${vmlinuz}" "${out_kernel}" ||
-	fail "failed to copy kernel to ${out_kernel}"
+    fail "failed to copy kernel to ${out_kernel}"
 
 { [ -z "${out_initramfs}" ] || cp "${initramfs}" "${out_initramfs}"; }  ||
-	fail "failed to copy initramfs to ${out_initramfs}"
+    fail "failed to copy initramfs to ${out_initramfs}"
 
 debug 1 "fixing grub entry in partimg"
 tmp_part="$TEMP_D/part.img.disk"
 cp "$out_partimg" "$tmp_part" &&
-	mount -o loop "$tmp_part" "$mp" && UMOUNT="$mp" ||
-	fail "failed to mount $tmp_part"
+    mount -o loop "$tmp_part" "$mp" && UMOUNT="$mp" ||
+    fail "failed to mount $tmp_part"
 sed -i 's/(hd0)/(hd0,0)/' "$mp/boot/grub/menu.lst" ||
-	fail "failed to edit /boot/grub/menu.lst in image"
+    fail "failed to edit /boot/grub/menu.lst in image"
 umount "$mp" && UMOUNT="" ||
-	fail "failed to unmount partimg"
+    fail "failed to unmount partimg"
 
 debug 1 "creating disk image"
-out=$(PATH=$xgrubd:$PATH part2disk --grub1 "$tmp_part" "$out_diskimg.raw" 2>&1) ||
-	fail "failed to create disk image: $out"
+out=$(PATH=$xgrubd:$PATH part2disk --grub1 "$tmp_part" \
+    "$out_diskimg.raw" 2>&1) ||
+    fail "failed to create disk image: $out"
 qemu-img convert -O qcow2 -c "$out_diskimg.raw" "$out_diskimg" ||
-	fail "failed to convert disk image"
+    fail "failed to convert disk image"
 rm -f "$out_diskimg.raw" "$tmp_part"
 
 if [ -n "${SUDO_USER}" ]; then
-	u=${SUDO_USER}
-	g=$(id -g "${u}") || g=${u}
-	chown "${u}:${g}" -R "$out_d" ||
-		fail "failed to grant ownership of ${u}:${g} to ${u}:${g}"
+    u=${SUDO_USER}
+    g=$(id -g "${u}") || g=${u}
+    chown "${u}:${g}" -R "$out_d" ||
+        fail "failed to grant ownership of ${u}:${g} to ${u}:${g}"
 fi
 
 echo "wrote ${out_partimg}"
@@ -315,3 +314,5 @@ echo "wrote ${out_blankimg}"
 echo "wrote ${out_filesys_lxc}"
 
 exit 0
+
+# vi: tabstop=4 expandtab
diff --git a/bin/mirror-dump-sstream-data b/bin/mirror-dump-sstream-data
--- a/bin/mirror-dump-sstream-data
+++ b/bin/mirror-dump-sstream-data
@@ -1,41 +1,39 @@
 #!/bin/bash
 set -f
-#
-# 
-# 
+
 Usage() {
    cat <<EOF
 Usage: ${0##*/} mirror_dir
 
-  write tab delimited data for simple streams 'tab2streams' input.
+    write tab delimited data for simple streams 'tab2streams' input.
 
-  Example:
+    Example:
 
-    bzr branch lp:simplestreams simplestreams
-    bzr branch lp:cirros cirros
+      bzr branch lp:simplestreams simplestreams
+      bzr branch lp:cirros cirros
 
-    ./cirros/bin/mirror-dump-sstream-data "\$mirror_d" > mdata.txt
-    ./simplestreams/tools/tenv tab2streams mdata.txt cirros-streams.d
+      ./cirros/bin/mirror-dump-sstream-data "\$mirror_d" > mdata.txt
+      ./simplestreams/tools/tenv tab2streams mdata.txt cirros-streams.d
 
-    ./simplestreams/tools/tenv env -u GNUPGHOME \
-       SS_GPG_BATCH=1 SS_GPG_DEFAULT_KEY=A5DDB840  \
-       js2signed cirros-streams.d
+      ./simplestreams/tools/tenv env -u GNUPGHOME \
+         SS_GPG_BATCH=1 SS_GPG_DEFAULT_KEY=A5DDB840  \
+         js2signed cirros-streams.d
 EOF
 }
 
 datefortag() {
-   local loginfo ts out repo="${CIRROS_BZR:-.}"
-   local spec="$1" fmt="${2:-+%Y%m%d}"
-   loginfo=$(bzr log "$repo" --log-format=long --revision "$spec") ||
-      { error "couldn't bzr log tag:$i"; return 1; }
-   ts=$(echo "$loginfo" | sed -n '/^timestamp:/s,.*: ,,p') &&
-      [ -n "$ts" ] || {
-         error "failed to get timestamp from log for $spec";
-         return 1;
-   }
-   out=$(date --date="$ts" "$fmt") ||
-      { error "failed convert of '$ts' to format=$fmt"; return 1; }
-   _RET="$out"
+    local loginfo ts out repo="${CIRROS_BZR:-.}"
+    local spec="$1" fmt="${2:-+%Y%m%d}"
+    loginfo=$(bzr log "$repo" --log-format=long --revision "$spec") ||
+        { error "couldn't bzr log tag:$i"; return 1; }
+    ts=$(echo "$loginfo" | sed -n '/^timestamp:/s,.*: ,,p') &&
+        [ -n "$ts" ] || {
+            error "failed to get timestamp from log for $spec";
+            return 1;
+    }
+    out=$(date --date="$ts" "$fmt") ||
+        { error "failed convert of '$ts' to format=$fmt"; return 1; }
+    _RET="$out"
 }
 
 error() { echo "$@" 1>&2; }
@@ -50,11 +48,12 @@ fi
 
 OIFS="$IFS"
 declare -A VERSION2SERIAL
-VERSION2SERIAL=( [0.3.0]="20111020" [0.3.1]="20130207"
-                 [0.3.1~pre1]="20120611" [0.3.1~pre3]="20120827"
-                 [0.3.1~pre4]="20130111" [0.3.2~pre1]="20130513"
-                 [0.3.2~pre2]="20131218" [0.3.2~pre3]="20140315"
-                 [0.3.2]="20140317"
+VERSION2SERIAL=(
+    [0.3.0]="20111020" [0.3.1]="20130207"
+    [0.3.1~pre1]="20120611" [0.3.1~pre3]="20120827"
+    [0.3.1~pre4]="20130111" [0.3.2~pre1]="20130513"
+    [0.3.2~pre2]="20131218" [0.3.2~pre3]="20140315"
+    [0.3.2]="20140317"
 )
 
 #content-id product_name version_name img_name [key=value [key=value]]
@@ -67,59 +66,61 @@ cd "$top_d"
 IFS=$'\n'; files=( $(find . -type f -printf "%p|%s\n") ); IFS="$OIFS"
 
 for ent in "${files[@]}"; do
-   IFS="|"; set -- $ent; IFS="$OIFS"
-   path=${1#./}
-   size=${2}
+    IFS="|"; set -- $ent; IFS="$OIFS"
+    path=${1#./}
+    size=${2}
 
-   case "$path" in
-      *-uec.tar.gz|*-disk.img|*-rootfs.img|*-lxc.tar.gz) :;;
-      *) continue;;
-   esac
-   IFS="/"; set -- $path; IFS=$OIFS
-   version="$1"; fname="$2";
-   serial="${VERSION2SERIAL[$version]}"
-   if [ -z "$serial" ]; then
-      datefortag "tag:$version" ||
-         fail "serial not found for $version!"
-      serial="$_RET"
-      VERSION2SERIAL[$version]="$serial"
-   fi
+    case "$path" in
+        *-uec.tar.gz|*-disk.img|*-rootfs.img|*-lxc.tar.gz) :;;
+        *) continue;;
+    esac
+    IFS="/"; set -- $path; IFS=$OIFS
+    version="$1"; fname="$2";
+    serial="${VERSION2SERIAL[$version]}"
+    if [ -z "$serial" ]; then
+        datefortag "tag:$version" ||
+            fail "serial not found for $version!"
+        serial="$_RET"
+        VERSION2SERIAL[$version]="$serial"
+    fi
 
-   # tokenize cirros-0.3.1~pre4-x86_64-lxc.tar.gz, baseproduct gets 'cirros'
-   IFS="-"; set -- $fname; IFS="$OIFS"
-   baseproduct="$1"; _version="$2"; arch="$3"; ftype="$4"
+    # tokenize cirros-0.3.1~pre4-x86_64-lxc.tar.gz, baseproduct gets 'cirros'
+    IFS="-"; set -- $fname; IFS="$OIFS"
+    baseproduct="$1"; _version="$2"; arch="$3"; ftype="$4"
 
-   # tokenize 0.3.1~pre1 or 0.3.0
-   extra=${version#*~}; [ "$extra" = "$version" ] && extra=""
-   tmp=${version%$extra}
-   IFS="."; set -- ${version%$extra}; IFS="$IOFS"
-   vmaj="$1"; vmin="$2"; vmic="$3"
+    # tokenize 0.3.1~pre1 or 0.3.0
+    extra=${version#*~}; [ "$extra" = "$version" ] && extra=""
+    tmp=${version%$extra}
+    IFS="."; set -- ${version%$extra}; IFS="$IOFS"
+    vmaj="$1"; vmin="$2"; vmic="$3"
 
-   [ -z "$extra" ] && stream="released" || stream="devel"
+    [ -z "$extra" ] && stream="released" || stream="devel"
 
-   # productname is "net.cirros-cloud[.devel]:standard:0.3:arch"
-   rdns="net.cirros-cloud"
-   [ "$stream" = "released" ] || rdns="${rdns}.${stream}"
-   product_name="$rdns:standard:$vmaj.$vmin:$arch"
-   content_id="${content_id_base//%(stream)s/${stream}}"
+    # productname is "net.cirros-cloud[.devel]:standard:0.3:arch"
+    rdns="net.cirros-cloud"
+    [ "$stream" = "released" ] || rdns="${rdns}.${stream}"
+    product_name="$rdns:standard:$vmaj.$vmin:$arch"
+    content_id="${content_id_base//%(stream)s/${stream}}"
 
-   req_out=""
-   for item in "$content_id" "$product_name" "$serial" "$ftype"; do
-      req_out="${req_out}${tab}${item}"
-   done
-   req_out=${req_out#${tab}}
+    req_out=""
+    for item in "$content_id" "$product_name" "$serial" "$ftype"; do
+        req_out="${req_out}${tab}${item}"
+    done
+    req_out=${req_out#${tab}}
 
-   md5=$(md5sum "${path}") && md5="${md5%%  ${path}}"
-   sha256=$(sha256sum "${path}") && sha256="${sha256%%  ${path}}"
-   pubname="${baseproduct}-${version}-${arch}"
+    md5=$(md5sum "${path}") && md5="${md5%%  ${path}}"
+    sha256=$(sha256sum "${path}") && sha256="${sha256%%  ${path}}"
+    pubname="${baseproduct}-${version}-${arch}"
 
-   out=""
-   for i in ftype path arch version size sha256 md5 pubname stream; do
-      out="${out}${tab}${i}=${!i}"
-   done
-   out=${out#${tab}}
-   printf "%s\n" "${req_out}${tab}${out}"
-   #printf "
-   #echo "$content_id
-   #echo "version=$version fname=$fname stream=$stream product_name=$product_name"
+    out=""
+    for i in ftype path arch version size sha256 md5 pubname stream; do
+        out="${out}${tab}${i}=${!i}"
+    done
+    out=${out#${tab}}
+    printf "%s\n" "${req_out}${tab}${out}"
+    #printf "
+    #echo "$content_id
+    #echo "version=$version fname=$fname stream=$stream product_name=$product_name"
 done
+
+# vi: tabstop=4 expandtab
diff --git a/bin/part2disk b/bin/part2disk
--- a/bin/part2disk
+++ b/bin/part2disk
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #    part2disk - wrap a partition image in a disk image
 #
 #    Copyright (C) 2010 Canonical Ltd.
@@ -23,37 +23,37 @@ base_d=$(dirname $(readlink -f "${0}"))
 PATH="${PATH}:${base_d}"
 error() { echo "$@" 1>&2; }
 debug() {
-	[ "${DEBUG}" -ge "${1:-0}" ] && shift || return 0;
-	error "$@";
+    [ "${DEBUG}" -ge "${1:-0}" ] && shift || return 0;
+    error "$@";
 }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 getsize() {
-	local fname="$1" kname="" size=""
-	if [ -b "${fname}" ]; then
-		kname=$(readlink -f "${fname}") &&
-			size=$(awk '$4 == kn { print $3 * 1024 }' \
-		             	"kn=${kname##*/}" /proc/partitions) &&
-			[ -n "${size}" ] || {
-				error "failed to read size of ${fname} from /proc/partitions";
-				return 1;
-			}
-	else
-		size=$(stat --format "%s" "${fname}") || {
-			error "failed to get size of ${fname}"
-			return 1;
-		}
-	fi
-	_RET="$size"
+    local fname="$1" kname="" size=""
+    if [ -b "${fname}" ]; then
+        kname=$(readlink -f "${fname}") &&
+            size=$(awk '$4 == kn { print $3 * 1024 }' \
+                         "kn=${kname##*/}" /proc/partitions) &&
+            [ -n "${size}" ] || {
+                error "failed to read size of ${fname} from /proc/partitions";
+                return 1;
+            }
+    else
+        size=$(stat --format "%s" "${fname}") || {
+            error "failed to get size of ${fname}"
+            return 1;
+        }
+    fi
+    _RET="$size"
 }
 
 Usage() {
-	cat <<EOF
+    cat <<EOF
 Usage: ${0##*/} [options] partition-image disk-image
 
-   create disk image 'disk-image' with 'partition-image' in a partition
-   inside it.
+    create disk image 'disk-image' with 'partition-image' in a partition
+    inside it.
 
-   options:
+    options:
       -G | --grub       install grub to disk image mbr
          | --grub1      install grub1 to disk image mbr
       -s | --size  S    create the disk image of size 'S'.
@@ -63,27 +63,27 @@ EOF
 }
 bad_Usage() { Usage 1>&2; fail "$@"; }
 human2bytes() {
-   # converts size suitable for input to resize2fs to bytes
-   # s:512 byte sectors, K:kilobytes, M:megabytes, G:gigabytes
-   # none: block size of the image
-   local input=${1} defunit=${2:-1024}
-   local unit count;
-   case "$input" in
-      *s) count=${input%s}; unit=512;;
-      *K) count=${input%K}; unit=1024;;
-      *M) count=${input%M}; unit=$((1024*1024));;
-      *G) count=${input%G}; unit=$((1024*1024*1024));;
-      *)  count=${input}  ; unit=${2:-1024};;
-   esac
-   _RET=$((${count}*${unit}))
+    # converts size suitable for input to resize2fs to bytes
+    # s:512 byte sectors, K:kilobytes, M:megabytes, G:gigabytes
+    # none: block size of the image
+    local input=${1} defunit=${2:-1024}
+    local unit count;
+    case "$input" in
+        *s) count=${input%s}; unit=512;;
+        *K) count=${input%K}; unit=1024;;
+        *M) count=${input%M}; unit=$((1024*1024));;
+        *G) count=${input%G}; unit=$((1024*1024*1024));;
+        *)  count=${input}  ; unit=${2:-1024};;
+    esac
+    _RET=$((${count}*${unit}))
 }
 
 short_opts="b:c:Ghs:v"
 long_opts="grub1,grub,help,size:,verbose"
 getopt_out=$(getopt --name "${0##*/}" \
-	--options "${short_opts}" --long "${long_opts}" -- "$@") &&
-	eval set -- "${getopt_out}" ||
-	bad_Usage
+    --options "${short_opts}" --long "${long_opts}" -- "$@") &&
+    eval set -- "${getopt_out}" ||
+    bad_Usage
 
 ssize=${DEF_SECTOR_SIZE}
 size_in=""
@@ -91,16 +91,16 @@ grub_ptnum=1
 grub=0
 grub1=0
 while [ $# -ne 0 ]; do
-	cur=${1}; next=${2};
-	case "$cur" in
-		-G|--grub) grub=1;;
-		-G|--grub1) grub1=1;;
-		-h|--help) Usage; exit 0;;
-		-s|--size) size_in=$2; shift;;
-		-v|--verbose) DEBUG=$((${DEBUG}+1));;
-		--) shift; break;;
-	esac
-	shift;
+    cur=${1}; next=${2};
+    case "$cur" in
+        -G|--grub) grub=1;;
+        -G|--grub1) grub1=1;;
+        -h|--help) Usage; exit 0;;
+        -s|--size) size_in=$2; shift;;
+        -v|--verbose) DEBUG=$((${DEBUG}+1));;
+        --) shift; break;;
+    esac
+    shift;
 done
 
 [ $# -eq 2 ] || bad_Usage "must supply partition image and output file"
@@ -109,13 +109,13 @@ pimg=${1}
 dimg=${2}
 
 { [ ${grub} -eq 0 ] || phelper=$(command -v part2disk-grubhelper); } ||
-	fail "no part2disk-grubhelper in PATH"
+    fail "no part2disk-grubhelper in PATH"
 [ $grub1 -eq 0 ] || command -v grub >/dev/null || fail "no 'grub' in path";
 
 [ -f "${pimg}" -o -b "${pimg}" ] || fail "${pimg}: not a file or block device"
 
 getsize "$pimg" ||
-	fail "failed to get size of $pimg"
+    fail "failed to get size of $pimg"
 pimg_s="$_RET"
 
 # end_pad_sectors: room for secondary gpt
@@ -126,7 +126,7 @@ front_pad_sectors=$(($front_pad/$ssize))
 padding=$(($front_pad+$end_pad))
 pt_sector_pad=$(($ssize-(${pimg_s}%$ssize)))
 if [ $pt_sector_pad -eq $ssize ]; then
-	pt_sector_pad=0
+    pt_sector_pad=0
 fi
 pt_size=$(($pimg_s+$pt_sector_pad))
 pt_sectors=$(($pt_size/$ssize))
@@ -134,23 +134,23 @@ tot_size=$(($front_pad+$pt_size+$end_pad))
 tot_size_sectors=$(($tot_size/$ssize))
 
 if [ -n "${size_in}" ]; then
-	human2bytes "${size_in}" 1 || fail "failed to convert ${size_in} to bytes"
-	size=${_RET}
+    human2bytes "${size_in}" 1 || fail "failed to convert ${size_in} to bytes"
+    size=${_RET}
 else
-	# no size specified, get enough to fit part_img, 1M header and 1M end.
-	size=$((${pimg_s}+$padding+$pt_sector_pad))
+    # no size specified, get enough to fit part_img, 1M header and 1M end.
+    size=$((${pimg_s}+$padding+$pt_sector_pad))
 fi
 
 if [ -e "$dimg" ]; then
-	getsize "$dimg" ||
-		fail "failed to get size of $dimg"
-	dimg_s="$_RET"
+    getsize "$dimg" ||
+        fail "failed to get size of $dimg"
+    dimg_s="$_RET"
 else
-	dimg_s="$size"
+    dimg_s="$size"
 fi
 
 if [ "${dimg_s}" -lt "$size" ]; then
-	fail "size of $dimg ($dimg_s) not large enough to fit $size"
+    fail "size of $dimg ($dimg_s) not large enough to fit $size"
 fi
 
 debug 1 "input is ${pimg_s} bytes ($pt_sectors sectors of $ssize)."
@@ -160,50 +160,50 @@ debug 1 "padding $front_pad_sectors sectors at front," \
 
 debug 2 "zeroing first $front_pad_sectors sectors $dimg"
 dd if=/dev/zero of="${dimg}" bs=$ssize "count=${front_pad_sectors}" \
-	2>/dev/null ||
+    2>/dev/null ||
     fail "failed to write to ${dimg}"
 
 # copy partition image. this writes $pimg bytes even if that is
 # not divivisble by $ssize
 debug 2 "copying ${pimg} to partition in ${dimg}"
 dd if="$pimg" of="$dimg" seek=${front_pad_sectors} bs=$ssize conv=notrunc \
-	2>/dev/null ||
-	fail "failed to write ${pimg} into ${dimg}"
+    2>/dev/null ||
+    fail "failed to write ${pimg} into ${dimg}"
 
 # zero any unwritten portion of the final sector
 leftover=$(($ssize-(${pimg_s}%$ssize)))
 if [ $pt_sector_pad -ne 0 ]; then
-	debug 2 "finishing final sector with $pt_sector_pad bytes of zeros"
-	dd if=/dev/zero of="$dimg" bs=1 seek=$((${pimg_s}+${front_pad})) \
-		conv=notrunc count=$pt_sector_pad 2>/dev/null ||
-	fail "failed to finish final sector of $pimg"
+    debug 2 "finishing final sector with $pt_sector_pad bytes of zeros"
+    dd if=/dev/zero of="$dimg" bs=1 seek=$((${pimg_s}+${front_pad})) \
+        conv=notrunc count=$pt_sector_pad 2>/dev/null ||
+    fail "failed to finish final sector of $pimg"
 fi
 
 # we've now written front pad + round-sectors. now write end_pad
 debug 2 "writing final $end_pad_sectors sectors"
 dd if=/dev/zero "of=$dimg" bs=$ssize \
-	seek=$((($size/$ssize)-${end_pad_sectors})) count=${end_pad_sectors} \
-	conv=notrunc 2>/dev/null ||
-	fail "failed to write final 1M to $pimg"
+    seek=$((($size/$ssize)-${end_pad_sectors})) count=${end_pad_sectors} \
+    conv=notrunc 2>/dev/null ||
+    fail "failed to write final 1M to $pimg"
 
 sfdisk_in="${front_pad_sectors},$pt_sectors,L,*"
 debug 2 "writing partition table to ${dimg} ($sfdisk_in)"
 sfdisk_out=$(echo "$sfdisk_in" | sfdisk --force --unit=S "${dimg}" 2>&1)
 
 [ $? -eq 0 ] || {
-	error "${sfdisk_out}";
-	fail "failed to create partition table";
+    error "${sfdisk_out}";
+    fail "failed to create partition table";
 }
 
 if [ ${grub} -ne 0 ]; then
-	debug 2 "invoking part2disk-grubhelper ${dimg}"
-	sudo "${phelper}" "${dimg}" ||
-		fail "part2disk-grubhelper ${dimg} failed"
+    debug 2 "invoking part2disk-grubhelper ${dimg}"
+    sudo "${phelper}" "${dimg}" ||
+        fail "part2disk-grubhelper ${dimg} failed"
 fi
 
 if [ $grub1 -ne 0 ]; then
-	debug 2 "installing grub"
-	grub --no-floppy --batch <<EOF
+    debug 2 "installing grub"
+    grub --no-floppy --batch <<EOF
 device (hd0) $dimg
 root (hd0,0)
 setup (hd0)
@@ -212,4 +212,5 @@ EOF
 fi
 
 error "wrote to ${dimg}"
-# vi: ts=4 noexpandtab
+
+# vi: tabstop=4 expandtab
diff --git a/bin/prepare-grub b/bin/prepare-grub
--- a/bin/prepare-grub
+++ b/bin/prepare-grub
@@ -1,5 +1,4 @@
 #!/bin/bash
-# vi: ts=4 noexpandtab
 
 # these urls are for lucid release version of grub
 i386_url="https://launchpad.net/ubuntu/+archive/primary/+files/grub_0.97-29ubuntu60_i386.deb"
@@ -7,14 +6,14 @@ x86_64_url="https://launchpad.net/ubuntu/+archive/primary/+files/grub_0.97-29ubu
 TEMP_D=""
 
 Usage() {
-	cat <<EOF
+    cat <<EOF
 Usage: ${0##*/} out_d
-	prepare out_d for grub
-	creates 'bootgrub.tar' and 'grub' binary
+    prepare out_d for grub
+    creates 'bootgrub.tar' and 'grub' binary
 EOF
 }
 cleanup() {
-	[ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
+    [ -z "${TEMP_D}" -o ! -d "${TEMP_D}" ] || rm -Rf "${TEMP_D}"
 }
 error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
@@ -28,25 +27,27 @@ out_d=$(cd "$out_d_in" && pwd)
 mkdir -p "$out_d/dl"
 
 case "$(uname -m)" in
-	x86_64) url="${x86_64_url}";;
-	i?86) url="${i386_url}";;
+    x86_64) url="${x86_64_url}";;
+    i?86) url="${i386_url}";;
 esac
 
 TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/.${0##*/}.XXXXXX") ||
-	fail "failed to make tempd"
+    fail "failed to make tempd"
 trap cleanup EXIT
 
 deb="${out_d}/dl/${url##*/}"
 if [ ! -e "${deb}" ]; then
-	wget "${url}" -O "${TEMP_D}/deb" &&
-		mv "${TEMP_D}/deb" "$deb" || fail "failed download of ${url}"
+    wget "${url}" -O "${TEMP_D}/deb" &&
+        mv "${TEMP_D}/deb" "$deb" || fail "failed download of ${url}"
 fi
 
 cd "${TEMP_D}"
 dpkg -x "$deb" . &&
-	cp usr/sbin/grub "$out_d/grub" &&
-	mkdir -p boot/grub &&
-	cp usr/lib/grub/*/{stage1,stage2,e2fs_stage1_5} boot/grub &&
-	tar cf "${out_d}/bootgrub.tar" boot/ ||
-	fail "failed to create $out_d"
+    cp usr/sbin/grub "$out_d/grub" &&
+    mkdir -p boot/grub &&
+    cp usr/lib/grub/*/{stage1,stage2,e2fs_stage1_5} boot/grub &&
+    tar cf "${out_d}/bootgrub.tar" boot/ ||
+    fail "failed to create $out_d"
 exit 0
+
+# vi: tabstop=4 expandtab
diff --git a/bin/xmakedevs b/bin/xmakedevs
--- a/bin/xmakedevs
+++ b/bin/xmakedevs
@@ -1,15 +1,16 @@
-#!/bin/sh -e
-# vi: ts=4 noexpandtab
+#!/bin/bash
 #
 # this mimics function of buildroot's makedev
 # read a file like:
 #  <name>    <type>      <mode>  <uid>   <gid>   <major> <minor> <start> <inc>   <count>
 # and make files
+
+set -e
 DEBUG=${XMAKEDEV_DEBUG}
 Usage() {
-   cat <<EOF
+    cat <<EOF
 Usage: ${0##*/} file root
-  read file, and make devs apropriately under 'root'.
+    read file, and make devs apropriately under 'root'.
 
 file looks like:
   <name>    <type>      <mode>  <uid>   <gid>   <major> <minor> <start> <inc>   <count>
@@ -31,71 +32,73 @@ fail() { [ $# -eq 0 ] || error "$@" ; exit 1; }
 root="$2"
 
 if [ "$1" != "-" ]; then
-	exec < "$1" || fail "failed to redirect input from $1"
+    exec < "$1" || fail "failed to redirect input from $1"
 fi
 
 chmodchown() {
-	local mode=$1 uid=$2 gid=$3
-	shift 3;
-	[ "$mode" = "-" ] || chmod "$mode" "$@" || return
-	[ "$uid" = "-" ] || chown "$uid" "$@" || return
-	[ "$gid" = "-" ] || chgrp "$gid" "$@" || return
+    local mode=$1 uid=$2 gid=$3
+    shift 3;
+    [ "$mode" = "-" ] || chmod "$mode" "$@" || return
+    [ "$uid" = "-" ] || chown "$uid" "$@" || return
+    [ "$gid" = "-" ] || chgrp "$gid" "$@" || return
 }
 iswild() {
-	local star="\\*"
-	case "$1" in
-		*$star*) return 0;;
-	esac
-	return 1
+    local star="\\*"
+    case "$1" in
+        *$star*) return 0;;
+    esac
+    return 1
 }
 
 cd "$root" || fail "failed cd $root"
 
 while read line; do
-	line=${line%#*}
-	[ -n "$line" ] || continue
-	set -f
-	set -- $line
-	name=$1; type=$2; mode=$3; uid=$4; gid=$5; major=$6; minor=$7; start=$8; inc=$9; count="${10}"
-	set +f
-	files="./${name#/}"
-	if iswild "$name"; then
-		files=$(echo ./$name)
-		iswild "$files" && fail "wildcards in wildcards: $files"
-	fi
-	case "$type" in
-		f) 
-			for f in $files; do
-				$DEBUG mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
-			done
-			$DEBUG touch $files &&
-			$DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
-			fail "failed create file $files"
-			;;
-		d)
-			$DEBUG mkdir -p $files &&
-			$DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
-			fail "failed create dir $files"
-			;;
-		c|b)
-			for f in $files; do
-				$DEBUG mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
-			done
-			if [ "$count" = "-" ]; then
-				$DEBUG mknod $files $type $major $minor ||
-					fail "failed mknod"
-				$DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
-					fail "failed chmodchown '$mode' '$uid' '$gid' $files"
-			else
-				[ "$count" = "-" ] && count=1;
-				i=0
-				while [ $i -lt $count ]; do
-					fname="./$name"
-					$DEBUG mknod "$fname" "$type" "$major" "$(($minor+($i*$inc)))"
-					$DEBUG chmodchown "$fname" "$mode" "$uid" "$gid"
-					i=$(($i+1))
-				done
-			fi
-			;;
-	esac
+    line=${line%#*}
+    [ -n "$line" ] || continue
+    set -f
+    set -- $line
+    name=$1; type=$2; mode=$3; uid=$4; gid=$5; major=$6; minor=$7; start=$8; inc=$9; count="${10}"
+    set +f
+    files="./${name#/}"
+    if iswild "$name"; then
+        files=$(echo ./$name)
+        iswild "$files" && fail "wildcards in wildcards: $files"
+    fi
+    case "$type" in
+        f) 
+            for f in $files; do
+                $DEBUG mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
+            done
+            $DEBUG touch $files &&
+            $DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
+            fail "failed create file $files"
+            ;;
+        d)
+            $DEBUG mkdir -p $files &&
+            $DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
+            fail "failed create dir $files"
+            ;;
+        c|b)
+            for f in $files; do
+                $DEBUG mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
+            done
+            if [ "$count" = "-" ]; then
+                $DEBUG mknod $files $type $major $minor ||
+                    fail "failed mknod"
+                $DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
+                    fail "failed chmodchown '$mode' '$uid' '$gid' $files"
+            else
+                [ "$count" = "-" ] && count=1;
+                i=0
+                while [ $i -lt $count ]; do
+                    fname="./$name"
+                    $DEBUG mknod "$fname" "$type" "$major" "$(($minor+($i*$inc)))"
+                    $DEBUG chmodchown "$fname" "$mode" "$uid" "$gid"
+                    i=$(($i+1))
+                done
+            fi
+            ;;
+    esac
 done
+
+# vi: ts=4 expandtab
