bin/mirror-dump-sstream-data: sync with 0.3 branch

diff --git a/bin/mirror-dump-sstream-data b/bin/mirror-dump-sstream-data
--- a/bin/mirror-dump-sstream-data
+++ b/bin/mirror-dump-sstream-data
@@ -12,7 +12,7 @@ Usage: ${0##*/} mirror_dir
     Example:
 
       bzr branch lp:simplestreams simplestreams
-      git clone https://git.launchpad.net/~cirros-dev/cirros cirros
+      git clone https://git.launchpad.net/cirros cirros
 
       ./cirros/bin/mirror-dump-sstream-data "\$mirror_d" > mdata.txt
       ./simplestreams/tools/tenv tab2streams mdata.txt cirros-streams.d
@@ -23,18 +23,45 @@ Usage: ${0##*/} mirror_dir
 EOF
 }
 
-datefortag() {
-    local ts out
-    local spec="$1" fmt="${2:-+%Y%m%d}"
-    ts=$(git log --date=iso --pretty="%cd" -1 "$spec") ||
-        { error "couldn't git log $spec"; return 1; }
+datefortag_bzr() {
+    local loginfo ts out repo="${CIRROS_BZR:-.}"
+    local spec="tag:$1" fmt="${2:-+%Y%m%d}"
+    loginfo=$(bzr log "$repo" --log-format=long --revision "$spec") ||
+        { error "couldn't bzr log tag:$i"; return 1; }
+    ts=$(echo "$loginfo" | sed -n '/^timestamp:/s,.*: ,,p') &&
+        [ -n "$ts" ] || {
+            error "failed to get timestamp from log for $spec";
+            return 1;
+        }
     out=$(date --date="$ts" "$fmt") ||
         { error "failed convert of '$ts' to format=$fmt"; return 1; }
     _RET="$out"
 }
 
+datefortag() {
+    local spec="$1" fmt="${2:-+%Y%m%d}"
+    local repo="${CIRROS_GIT:-${CIRROS_BZR:-.}}"
+    if [ ! -d "$repo/.git" -a -d "$repo/.bzr" ]; then
+        datefortag_bzr "$@"
+        return
+    fi
+    spec=${spec//"~"/_} # git tags cannot contain ~
+    ts=$( cd "$repo" &&
+        git show --no-patch "--pretty=format:%ct" "$spec") ||
+        { error "failed to 'git show $spec' in $repo"; return 1; }
+    out=$(date --utc --date="@$ts" "$fmt") ||
+        { error "failed to convert seconds '$ts' to format $fmt"; return 1; }
+    _RET="$out"
+}
+
 [ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }
 [ "$#" -eq 1 ] || { Usage 1>&2; fail "must give mirror dir"; }
+
+if [ -z "$CIRROS_BZR" ]; then
+    CIRROS_BZR=$(t=$(readlink -f "$0") && cd "${t%/*}/.." && pwd)
+elif [ -z "$CIRROS_GIT" ]; then
+    CIRROS_GIT=$(t=$(readlink -f "$0") && cd "${t%/*}/.." && pwd)
+fi
 
 OIFS="$IFS"
 declare -A VERSION2SERIAL
@@ -68,7 +95,7 @@ for ent in "${files[@]}"; do
     version="$1"; fname="$2";
     serial="${VERSION2SERIAL[$version]}"
     if [ -z "$serial" ]; then
-        datefortag "tag:$version" ||
+        datefortag "$version" ||
             fail "serial not found for $version!"
         serial="$_RET"
         VERSION2SERIAL[$version]="$serial"
