xmakedevs: apply chmod and chown permissions on device nodes
This fixes a bug that resulted in entries in /dev having incorrect
permissions.

diff --git a/bin/xmakedevs b/bin/xmakedevs
--- a/bin/xmakedevs
+++ b/bin/xmakedevs
@@ -66,7 +66,7 @@ while read line; do
 	case "$type" in
 		f) 
 			for f in $files; do
-				mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
+				$DEBUG mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
 			done
 			$DEBUG touch $files &&
 			$DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
@@ -79,10 +79,13 @@ while read line; do
 			;;
 		c|b)
 			for f in $files; do
-				mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
+				$DEBUG mkdir -p "${f%/*}" || fail "failed to make ${f%/*}";
 			done
 			if [ "$count" = "-" ]; then
-				$DEBUG mknod $files $type $major $minor
+				$DEBUG mknod $files $type $major $minor ||
+					fail "failed mknod"
+				$DEBUG chmodchown "$mode" "$uid" "$gid" $files ||
+					fail "failed chmodchown '$mode' '$uid' '$gid' $files"
 			else
 				[ "$count" = "-" ] && count=1;
 				i=0
