move resize over to 'cirros-per once'

diff --git a/src/etc/init.d/resizefs b/src/etc/init.d/resizefs
--- a/src/etc/init.d/resizefs
+++ b/src/etc/init.d/resizefs
@@ -1,25 +1,22 @@
 #!/bin/sh
 # vi: ts=4 noexpandtab
-# load modules
 
 case "$1" in
 	start)
 		lxc-is-container && exit 0
 		[ -e /dev/root ] || exit 0
-		. /usr/share/cloud/functions
-		[ "${RESIZE_FS:-0}" = "0" ] && exit 0
-		marked once resizefs && exit 0
-		sh -c 'o=/tmp/resize.out;
-		       resize2fs /dev/root >$o 2>&1 &&
-		       rm -f $o && exit 0 ||
-		       echo "resize failed!" 1>&2;
-		       cat $o 1>&2; exit 1;' resizefs &
-		mark once resizefs
+		cirros-per once resizefs \
+			sh -c 'o=/tmp/resize.out;
+				resize2fs /dev/root >$o 2>&1 &&
+				rm -f $o && exit 0 ||
+				echo "resize failed!" 1>&2;
+				cat $o 1>&2; exit 1;' resizefs &
 		;;
 	stop|restart|reload) : ;;
-  *)
-	echo $"Usage: $0 {start}"
-	exit 1
+	*)
+		echo $"Usage: $0 {start}"
+		exit 1
+		;;
 esac
 
 exit $?
