growpart/growroot: enable and resize partition and root while online
kernels 3.8+ support updating partition sizes while partitions are
mounted and growpart supports doing that.  We no longer have to use growpart
from the initramfs.  Run it instead from 'resizefs' init script.

kernels 3.3+ resize fast enough to enable this by default.  But background
the operation by default.

We background because our root filesystems are so small (~24M) and the
targets so comparatively large (probably at least 2G) that it is still
time consuming (24M -> 2G took 20 seconds in test).

diff --git a/src/bin/growroot b/src/bin/growroot
--- a/src/bin/growroot
+++ b/src/bin/growroot
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-ROOT=$1
+ROOT=${1:-/dev/root}
 
-fail() { echo "growroot: FAIL:" "$@"; }
+fail() { echo "growroot: FAIL:" "$@" 1>&2; exit 1; }
 msg() { echo "$@"; }
 
 # figure out what disk ROOT is on
@@ -30,48 +30,19 @@ partnum=${rootdev#${rootdisk}}
 
 # if growpart fails, exit. its failure messages should go
 # to stderr, so they'll get to the console
-out=$(growpart "${rootdisk}" "${partnum}" ) ||
-	{ msg "${out}"; exit 1; }
+out=$(growpart "${rootdisk}" "${partnum}")
+ret=$?
 
 # if growpart output starts with 'CHANGED:' then it did something.
 # anything else, exit
-case "${out}" in
-	CHANGED:*) echo "GROWROOT: $out";;
+case "$ret" in
+	0|1) echo "GROWROOT: $out";;
 	*)
 		echo "$out";
-		exit 0;;
+		exit $ret;;
 esac
 
-was_mounted=false
-while read src mp fstype opts o p; do
-	if [ "$src" = "$ROOT" ]; then
-		FS=$fstype;
-		OPTS=$opts;
-		MP=$mp
-		was_mounted=true
-	fi
-done < /proc/mounts
-
-if $was_mounted; then
-	umount "${ROOT}" || fail "failed to umount ${ROOT}";
-fi
-
-sfdisk -R "${rootdisk}" ||
-	msg "failed to re-read partition for ${rootdisk}"
-
-if $was_mounted; then
-	# this is taken from 'mountroot' function
-	#   see /usr/share/initramfs-tools/scripts/local
-	i=0
-	while [ $i -lt 50 ]; do
-		mount -o "$OPTS" "$ROOT" "$MP" >/dev/null 2>&1 && exit 0
-		i=$(($i+1))
-		sleep .2
-	done
-	[ $i -eq 50 ] && fail "unable to remount, that is bad"
-fi
-
-# write to /etc/grownroot-grown. most likely this wont work (readonly)
+# write to /etc/grownroot-grown.
 { date --utc > "${rootmnt}/etc/growroot-grown" ; } >/dev/null 2>&1 || :
 
 # vi: ts=4 noexpandtab
diff --git a/src/etc/init.d/resizefs b/src/etc/init.d/resizefs
--- a/src/etc/init.d/resizefs
+++ b/src/etc/init.d/resizefs
@@ -1,7 +1,8 @@
 #!/bin/sh
 # vi: ts=4 noexpandtab
 
-RESIZE_MODE="disabled"
+RESIZE_MODE="background"
+GROWROOT="enabled"
 if [ -f /etc/default/resizefs ]; then
 	. /etc/default/resizefs
 fi
@@ -10,6 +11,12 @@ case "$1" in
 	start)
 		lxc-is-container && exit 0
 		[ -e /dev/root ] || exit 0
+		case "$GROWROOT" in
+			disabled|off|0) :;;
+			*)
+				growroot /dev/root ||
+					{ echo "failed growing /dev/root"; exit 1; }
+		esac
 		# here we have to use start-stop-daemon or the resize
 		# process gets killed when rc.sysinit ends (LP: #1261710)
 		case "$RESIZE_MODE" in
